# Generated by Django 4.0.1 on 2022-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_status_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default=True, max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default=True, max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
