# Generated by Django 4.0.1 on 2022-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название сайта')),
                ('logo', models.ImageField(null=True, upload_to='logo', verbose_name='Логотип')),
                ('keywords', models.CharField(max_length=200, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(null=True, verbose_name='Описание сайта')),
                ('location', models.CharField(blank=True, help_text='Мы находимся по адресу ул.Ленина 232', max_length=100, null=True, verbose_name='Локация')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='email')),
                ('time_work', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время работы')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='telegram')),
                ('watsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='watsapp')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='instagram')),
            ],
            options={
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
