# Generated by Django 4.0.1 on 2022-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slier_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slier_promotion',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='slier_promotion',
            name='image2',
            field=models.ImageField(null=True, upload_to='slider_promotion/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='slier_promotion',
            name='image3',
            field=models.ImageField(null=True, upload_to='slider_promotion/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='slier_promotion',
            name='image4',
            field=models.ImageField(null=True, upload_to='slider_promotion/', verbose_name='Картинка'),
        ),
    ]
