# Generated by Django 4.0.1 on 2022-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_image_slier_promotion_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='detail_news',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
