# Generated by Django 4.0.1 on 2022-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата примера')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('message', models.TextField(null=True, verbose_name='Сообщение')),
                ('send_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name_plural': 'Записи на пропуск',
            },
        ),
    ]
