# Generated by Django 4.0.1 on 2022-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='email')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('reviews', models.CharField(max_length=500, null=True, verbose_name='Отзыв')),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время добавления')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
